### ISSUE TITLE
Rename this package and repo `astrodb_utils`

### ISSUE THREAD

**Issue by kelle** [astrodbtoolkit/astrodb_utils#22]
In SIMPLE, we decided that `scripts` are "one-off" scripts and `utils` are the helper functions.  In keeping consistent with that thinking, this package should be named `astrodb_utils`.

**Comment by kelle** [comment]
@arjunsavel , thoughts?

**Comment by arjunsavel** [comment]
I think the change makes sense to me! Especially with `utils.py` being the main file in here right now.

**Comment by arjunsavel** [comment]
@kelle just confirming that we'd like to make the change!

**Comment by kelle** [comment]
YES! If you want to take that on, that would be super useful. It's gonna be non-trivial.

**Comment by arjunsavel** [comment]
on it 🫡

**Comment by arjunsavel** [comment]
Done! #37
