### ISSUE TITLE
provide instructions on how to setup ADS TOKEN

### ISSUE THREAD

**Issue by kelle** [astrodbtoolkit/astrodb_utils#31]
[moved from https://github.com/SIMPLE-AstroDB/SIMPLE-db/issues/152]

For the `ingest_publication` function, an ADS TOKEN environment variable should be set. We should provide instructions on how to do that.

make account on ADS and get the token from ADS: https://ui.adsabs.harvard.edu/help/api/

Then add it via an environment variable in your .bashrc or whatever init file you have.

`export ADS_TOKEN="<your token>"`

**Comment by arjunsavel** [comment]
Question: is this something we'd want in the README, or in the readthedocs documentation? if the latter, we should chat about how we want to structure the documentation in general.

**Comment by kelle** [comment]
I think this goes in the RTD.  

If we need to talk about structuring the documentation, maybe open a new issue and ask some specific questions?

**Comment by kelle** [comment]
Done. https://astrodb-utils.readthedocs.io/en/latest/pages/ingesting_publications.html#set-up-ads-token
