### ISSUE TITLE
Question re:"*" usage in functions

### ISSUE THREAD

**Issue by dr-rodriguez** [astrodbtoolkit/astrodb_utils#47]
What is `*` supposed to be in:
https://github.com/astrodbtoolkit/astrodb_utils/blob/640b6bf375125f8ef912e61b67f7956868103118/astrodb_utils/utils.py#L122 

That's used throughout several functions, but it's not clear to me what it represents or how it's meant to be used. If this is meant to be `*args` isn't it missing the args part of it so it can be referred to in the code?

**Comment by kelle** [comment]
So glad you asked!  It *forces* the keyword parameters to be keyword parameters. If the * is not there and the user provides the right amount of positional parameters, python will guess those positional parameters to be the keywords!  

It's explained in [PEP 3102](https://legacy.python.org/dev/peps/pep-3102/)

**Comment by dr-rodriguez** [comment]
Interesting. I didn't know that, but in hindsight it makes sense!
